apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomwebsite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomwebsite
  template:
    metadata:
      labels:
        app: ecomwebsite
    spec:
      containers:
      - name: ecomwebsite
        image: vedantonkar24/ecomwebsite-image:latest
        ports:
        - containerPort: 80  # Changed from 3000 to 80 for Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: ecomwebsite-service
spec:
  selector:
    app: ecomwebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Changed from 3000 to 80 to match container port
  type: NodePort
