apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomwebsite-deployment
  labels:
    app: ecomwebsite
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ecomwebsite
  template:
    metadata:
      labels:
        app: ecomwebsite
    spec:
      containers:
      - name: ecomwebsite
        image: vedantonkar24/ecomwebsite-image:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ecomwebsite-service
  labels:
    app: ecomwebsite
spec:
  selector:
    app: ecomwebsite
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
